[package]
name = "hdmd5sum1310"
version = "0.1.0"
authors = ["jp <jpercyasnet@yahoo.com>"]
edition = "2021"
publish = false

[dependencies]
iced = "^0"
rfd = { version = "^0", features = ["xdg-portal"] }
chrono = "^0"
walkdir = "^0"
md5 = "^0"
